# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKGUQbGLPx1eljhQkRi-35xoN4mBFT_-
"""

from fastapi import FastAPI
from pydantic import BaseModel
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import torch.nn.functional as F

app = FastAPI(title="Spam Detection API", description="BERT based Spam/Ham Classifier with Explanation")

# Load model & tokenizer (from your extracted folder)
MODEL_PATH = "spam_model"   # <-- folder where you extracted the zip model

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)
model.eval()

# Request schema
class TextRequest(BaseModel):
    text: str

# Spam keywords list (for explanation only)
SPAM_KEYWORDS = [
    "free", "win", "winner", "lottery", "prize", "click", "urgent", "verify",
    "limited", "offer", "congratulations", "account", "password", "login",
    "bank", "credit", "card", "money", "reward", "bonus"
]

def get_spam_keywords(text: str):
    text_lower = text.lower()
    found = [word for word in SPAM_KEYWORDS if word in text_lower]
    return found


@app.post("/predict")
def predict_spam(request: TextRequest):
    text = request.text.strip()

    # Tokenize
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

    # Model prediction
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        probs = F.softmax(logits, dim=1).tolist()[0]

    # Assuming: 0 = HAM, 1 = SPAM
    ham_prob = round(probs[0] * 100, 2)
    spam_prob = round(probs[1] * 100, 2)

    if spam_prob > ham_prob:
        prediction = "SPAM"
    else:
        prediction = "HAM"

    # Explanation logic (IMPORTANT – no mixing)
    spam_words = get_spam_keywords(text)

    if prediction == "SPAM":
        if spam_words:
            reason = f"Message contains spam-related keywords: {', '.join(spam_words)}"
        else:
            reason = "Model detected spam patterns such as urgency, promotional tone, or suspicious intent"
    else:
        reason = "Model is confident this is a normal, non-promotional personal message"

    return {
        "text": text,
        "prediction": prediction,
        "probability": {
            "HAM": ham_prob,
            "SPAM": spam_prob
        },
        "reason": reason
    }


@app.get("/")
def root():
    return {"message": "Spam Detection API is running"}