# -*- coding: utf-8 -*-
"""dash_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BZQJfXNXbjwZpeY6oY4DnRMBrJwGy2c
"""

import re
import torch
import dash
from dash import html, dcc
from dash.dependencies import Input, Output, State
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch.nn.functional as F

# ----------------------
# CONFIG
# ----------------------
MODEL_PATH = "./spam_model"   # make sure this folder exists
CONFIDENCE_MARGIN = 0.15           # margin between spam and ham for strong label
SPAM_KEYWORDS = [
    "free", "win", "winner", "prize", "cash", "click", "offer",
    "urgent", "limited", "now"
]

# ----------------------
# LOAD MODEL
# ----------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)
model.eval()

# ----------------------
# HELPER FUNCTIONS
# ----------------------
def predict_probs(text: str):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=128
    )
    with torch.no_grad():
        outputs = model(**inputs)
        probs = F.softmax(outputs.logits, dim=1).squeeze()

    ham_prob = probs[0].item()
    spam_prob = probs[1].item()
    return spam_prob, ham_prob


def generate_reasons(text: str, spam_prob: float, ham_prob: float, label: str):
    reasons = []
    text_lower = text.lower()

    # suspicious keywords
    found = [w for w in SPAM_KEYWORDS if w in text_lower]
    if found:
        reasons.append(f"Contains suspicious keywords: {', '.join(found)}")

    # URL / link
    if re.search(r"http[s]?://|www\.", text_lower):
        reasons.append("Contains a URL or link")

    # caps check
    if sum(1 for c in text if c.isupper()) > len(text) * 0.4:
        reasons.append("Excessive use of capital letters")

    # exclamation check
    if text.count("!") >= 3:
        reasons.append("Too many exclamation marks")

    # confidence-based reason only when borderline
    if label == "BORDERLINE":
        reasons.append("Model confidence is low (borderline message)")

    if not reasons:
        reasons.append("No strong spam indicators detected")

    return reasons


def decide_label(spam_prob: float, ham_prob: float):
    # spam if spam_prob is ahead by margin
    if spam_prob - ham_prob >= CONFIDENCE_MARGIN:
        return "SPAM 🚨"
    # ham if ham_prob is ahead by margin
    elif ham_prob - spam_prob >= CONFIDENCE_MARGIN:
        return "HAM ✅"
    else:
        return "BORDERLINE ⚠️"


# ----------------------
# DASH APP
# ----------------------
app = dash.Dash(__name__)

app.layout = html.Div(
    style={"width": "70%", "margin": "auto", "fontFamily": "Arial"},
    children=[
        html.H1("Spam Detection App"),

        dcc.Textarea(
            id="input-text",
            placeholder="Enter your message here...",
            style={"width": "100%", "height": 150},
        ),

        html.Br(),
        html.Button("Check", id="check-btn", n_clicks=0),
        html.Hr(),

        html.Div(id="result-area"),
    ]
)


@app.callback(
    Output("result-area", "children"),
    Input("check-btn", "n_clicks"),
    State("input-text", "value"),
)
def analyze_text(n_clicks, text):
    if not n_clicks or not text or not text.strip():
        return ""

    spam_prob, ham_prob = predict_probs(text)
    label = decide_label(spam_prob, ham_prob)
    reasons = generate_reasons(text, spam_prob, ham_prob, label)

    return html.Div(
        children=[
            html.H2(label),
            html.P(
                f"Spam: {spam_prob:.2f} | Ham: {ham_prob:.2f}",
                style={"fontWeight": "bold"},
            ),
            html.H4("Reason"),
            html.Ul([html.Li(r) for r in reasons]),
        ]
    )


# ----------------------
# RUN
# ----------------------
if __name__ == "__main__":
    app.run(debug=True)